version: '3'

services:
  sonarqube:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    stdin_open: true
    tty: true
    ports:
      - "9001:9000"
    volumes:
      - ./repositories:/opt/sonarqube/repositories

volumes:
    repositories:
